import { NextRequest, NextResponse } from 'next/server';
import { getAuthUserFromRequest } from '@/lib/auth';
import { getUserAccess } from '@/lib/access';
import { getSupabaseClient } from '@/lib/supabase';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await getAuthUserFromRequest(request);
  if (!user) {
    return NextResponse.json({ error: 'Authentication required.' }, { status: 401 });
  }

  const access = await getUserAccess(user.id, user.email);
  if (!access.canAccessFeature('content_studio')) {
    return NextResponse.json({ error: 'Content Studio requires a Pro plan or higher.' }, { status: 403 });
  }

  const { id } = await params;
  if (!UUID_RE.test(id)) {
    return NextResponse.json({ error: 'Invalid id.' }, { status: 400 });
  }

  const supabase = getSupabaseClient();

  // Verify item exists and belongs to user
  const { data: item, error: fetchError } = await supabase
    .from('content_studio_items')
    .select('*')
    .eq('id', id)
    .eq('user_id', user.id)
    .single();

  if (fetchError || !item) {
    return NextResponse.json({ error: 'Content item not found.' }, { status: 404 });
  }

  // Update status to generating
  const { error: updateError } = await supabase
    .from('content_studio_items')
    .update({
      status: 'brief_generating',
      workflow_progress: { step: 1, progress: 0, currentTask: 'Web Research' },
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);

  if (updateError) {
    return NextResponse.json({ error: updateError.message }, { status: 500 });
  }

  // Simulate brief generation workflow (in production, this would call AI services)
  // For now, generate a placeholder brief after a short delay
  const workflowSteps = [
    { step: 1, progress: 20, currentTask: 'Web Research' },
    { step: 2, progress: 40, currentTask: 'Quote Extraction' },
    { step: 3, progress: 60, currentTask: 'Outline Generation' },
    { step: 4, progress: 80, currentTask: 'Brief Generation' },
    { step: 5, progress: 100, currentTask: 'Complete' },
  ];

  // Simulate async generation: mark as brief_ready with placeholder content
  const briefContent = `# ${item.title}\n\n## Overview\n\nThis is a generated brief for a **${item.content_type.replace(/_/g, ' ')}** about "${item.topic || item.title}".\n\n## Key Points\n\n- Point 1: Research-backed insight\n- Point 2: Industry analysis\n- Point 3: Actionable recommendation\n\n## Outline\n\n1. Introduction\n2. Background & Context\n3. Main Analysis\n4. Key Takeaways\n5. Conclusion\n\n---\n\n*Generated by Content Studio*`;

  await supabase
    .from('content_studio_items')
    .update({
      status: 'brief_ready',
      brief_markdown: briefContent,
      workflow_progress: workflowSteps[workflowSteps.length - 1],
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);

  return NextResponse.json({ ok: true, status: 'brief_generating' });
}
